#!/usr/bin/env python3
"""Generate chapter_ld_frames.inc — ROM lookup table mapping chapter ID → LD start frame.

Scans XML event files for <timestart frame="..."> attributes and chapter.id.* files
to build a 16-bit word table indexed by chapter ID.

Usage:
    python3 tools/generate_ld_frame_table.py \
        --events-dir data/events \
        --chapters-dir data/chapters \
        --output data/chapters/chapter_ld_frames.inc
"""
import argparse
import glob
import os
import re
import xml.etree.ElementTree as ET


def parse_args():
    p = argparse.ArgumentParser(description="Generate LD start-frame table for MSU-1 skip feature")
    p.add_argument("--events-dir", required=True, help="Directory containing *.xml event files")
    p.add_argument("--chapters-dir", required=True, help="Directory containing chapter subdirs with chapter.id.* files")
    p.add_argument("--output", required=True, help="Output .inc file path")
    return p.parse_args()


def build_chapter_id_map(chapters_dir):
    """Map chapter name → numeric ID from chapter.id.* files."""
    name_to_id = {}
    for id_file in glob.glob(os.path.join(chapters_dir, "*", "chapter.id.*")):
        dirname = os.path.basename(os.path.dirname(id_file))
        filename = os.path.basename(id_file)
        # chapter.id.465 → 465
        m = re.match(r"chapter\.id\.(\d+)", filename)
        if m:
            name_to_id[dirname] = int(m.group(1))
    return name_to_id


def parse_ld_frame_from_xml(xml_path):
    """Extract the LD start frame from an XML event file's <timestart frame="...">."""
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        # <chapter><timeline><timestart frame="1887" .../>
        timeline = root.find("timeline")
        if timeline is not None:
            timestart = timeline.find("timestart")
            if timestart is not None:
                frame_attr = timestart.get("frame")
                if frame_attr is not None:
                    return int(frame_attr)
    except ET.ParseError:
        pass
    return 0


def main():
    args = parse_args()

    # Build chapter name → ID map
    name_to_id = build_chapter_id_map(args.chapters_dir)
    if not name_to_id:
        raise RuntimeError(f"No chapter.id.* files found in {args.chapters_dir}")

    max_id = max(name_to_id.values())

    # Build chapter name → LD frame map from XML files
    name_to_frame = {}
    for xml_path in sorted(glob.glob(os.path.join(args.events_dir, "*.xml"))):
        name = os.path.splitext(os.path.basename(xml_path))[0]
        name_to_frame[name] = parse_ld_frame_from_xml(xml_path)

    # Build ID-indexed table
    table = [0] * (max_id + 1)
    for name, chapter_id in name_to_id.items():
        table[chapter_id] = name_to_frame.get(name, 0)

    # Write output
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", newline="\n") as f:
        f.write("; Auto-generated by generate_ld_frame_table.py — DO NOT EDIT\n")
        f.write("chapter_ld_start_table:\n")
        for chapter_id in range(max_id + 1):
            # Find name for comment
            names = [n for n, cid in name_to_id.items() if cid == chapter_id]
            name_comment = names[0] if names else "???"
            ld_frame = table[chapter_id]
            f.write(f"    .dw {ld_frame}    ; ch {chapter_id}: {name_comment}\n")

    print(f"Generated {args.output}: {max_id + 1} entries (max LD frame: {max(table)})")


if __name__ == "__main__":
    main()
