
  SCRIPT game_over

  ;kill active chapters and events
  lda.w #OBJECT.PROPERTIES.isChapter
  jsr abstract.Iterator.setProperties
  jsr abstract.Iterator.killOthers

  lda.w #OBJECT.PROPERTIES.isEvent
  jsr abstract.Iterator.kill.byProperties

  lda.w #OBJECT.PROPERTIES.isDash
  jsr abstract.Iterator.kill.byProperties

  lda.w #OBJECT.PROPERTIES.isHdma
  jsr abstract.Iterator.kill.byProperties

  lda.w #OBJID.Msu1
  jsr abstract.Iterator.kill.byId

  ;reset screen mode
  sep #$20
  lda.b #BGMODE_MODE_1 | BGMODE_PRIORITY_LAYER_3
  sta.w ScreenMode
  lda.w MainScreen
  and.b #(T_BG1_ENABLE | T_BG2_ENABLE | T_BG3_ENABLE | T_BG4_ENABLE) ~$ff
  sta.w MainScreen
  rep #$31

  ;clear VRAM and CGRAM
  jsr core.vram.init
  jsr core.cgram.clear

  ;fade to black then go to title screen
  NEW Brightness.CLS.PTR objBrightness

  lda #BRIGHTNESS.NONE
  CALL Brightness.set.MTD objBrightness

  NEW Script.CLS.PTR oopCreateNoPtr title_screen

  DIE
